### ISSUE TITLE
incorrect i386 decode f20f100d28330608

### ISSUE THREAD

**Issue by atlas0fd00m** [vivisect/vivisect#145]
f20f100d28330608

**Comment by atlas0fd00m** [comment]
these are all fucked.

.text:0x08063d3d  f30f1045f8       rep: movups xmm0,oword [ebp - 8]
.text:0x08063d42  f30f2ac8         rep: cvtpi2ps xmm1,mm0
.text:0x08063d46  f30f1055d0       rep: movups xmm2,oword [ebp - 48]
.text:0x08063d4b  f30f59ca         rep: mulps xmm1,xmm2
.text:0x08063d4f  f30f5cc1         rep: subps xmm0,xmm1
.text:0x08063d53  f30f5ac0         rep: cvtps2pd xmm0,xmm0
.text:0x08063d57  f20f1145f0       repnz: movups oword [ebp - 16],xmm0
.text:0x08063d5c  f20f100d70790908 repnz: movups xmm1,oword [loc_08097970]
.text:0x08063d64  f20f59c1         repnz: mulps xmm0,xmm1
.text:0x08063d68  f20f1145f0       repnz: movups oword [ebp - 16],xmm0


should be no rep prefix for them

**Comment by rakuy0** [comment]
Fixed (and used as test cases (thanks for that)) as part of #244
