### ISSUE TITLE
symboliks: instruction add eflags effects

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#146]
Is there a good reason that the effects for eflags commented out for the i386 add instruction?

ref: https://github.com/vivisect/vivisect/blob/master/vivisect/symboliks/archs/i386.py#L261

Its difficult to use `git blame` to determine the original committer, since the change was made back in the hg era. So, I'll ask here.

Can you think of a good reason not to re-enable them (after some testing)?

**Comment by atlas0fd00m** [comment]
very good question!  i have no reason for leaving it undone.  that sounds terrible.
