### ISSUE TITLE
unit tests?

### ISSUE THREAD

**Issue by atlas0fd00m** [vivisect/vivisect#165]
are unit tests ever used?
if so, how so?
i see lots of errors in the unit tests, but it seldom improves, only gets worse.  
i'm not sure how to fix some of them, and i don't have the same binaries as some.

**Comment by bat-serjo** [comment]
From my humble experience with the py3 port attempt, it seems the best option for a unit test would be:

Gather a bunch of wierd and problematic binaries (ctfs and crackmes) for every supported platform. 
Run vivisect on them in cli mode. Analyze the resulting .viv file for some pre-made determined contents.
Such a test does cover a wire range of functionality involves almost the whole stack and if the binary set is chosen correctly can produce almost 100% code coverage. Delphi binaries do hit the emulator hard.

To this point that is my best sulition: just throw binaries at the py3 port and compare the results with the py2 version and i keep finding things bugs in the py3 port.

**Comment by bat-serjo** [comment]
You can take a look at this storage format
https://github.com/bat-serjo/vivisect-py3/blob/refactor/vivisect/storage/utestresult.py
It does log almost all VIV events then goes to dump all functions disassembly sorted by address.
It's pretty usable for a quick and dirty diff
