### ISSUE TITLE
8d14f500000000 decodes incorrectly

### ISSUE THREAD

**Issue by atlas0fd00m** [vivisect/vivisect#211]

**Comment by atlas0fd00m** [comment]
Currently:
  .text:0x020b80fc  8d14f500000000   lea edx,dword [0x00000000 + esi * 8]

Should be:
  lea     edx, ds:0[esi*8]

**Comment by rakuy0** [comment]
@atlas0fd00m Is this still valid (and do you have the binary that displays it)? 

I've got a super small test binary that has that byte string in it, and nasm, binary ninja, vivisect, https://onlinedisassembler.com/odaweb/, and https://defuse.ca/online-x86-assembler.htm all seem to agree that 8d14f500000000 all encodes/decodes to lea edx,dword [0x00000000 + esi * 8].

Or does whatever binary this is also have some other segment shenanigans going on and we need to push segment info through the decoding or analysis passes?

**Comment by atlas0fd00m** [comment]
damn, i'm dense.  for some reason i thought that said gs:.
closed.
