### ISSUE TITLE
ImportError:No module named constants vstruct.constants  as vs_const 

### ISSUE THREAD

**Issue by maoguai** [vivisect/vivisect#279]
i was able to use vivisect before ,but now when i import vivisect, i meet ImportError problem

**Comment by rakuy0** [comment]
Odd. There's only one place we call `import vstruct.constants as vs_const` and that's in vivisect/base.py. That hasn't changed in a long time and the CI builds for vivisect's master branch say they still work. So that's a bit weird.

So a couple questions to try and help narrow down the problem:
* Do you have any idea as to what changed to make it not work all of a sudden? Was it a git pull or something else?
* What vivisect branch and commit hash are you on?
* Do you have any changes to vivisect sitting on your checkout?
* Just in case, do you have the full exception traceback?
* What python version are you on?
* What's your PYTHONPATH env var look like?

**Comment by maoguai** [comment]
![image](https://user-images.githubusercontent.com/21984318/79932631-8decad00-8480-11ea-8bd7-4d60359efec2.png)
I use python 2.7,i meet this problem that i just import vivisect .
I use sys.path.append() to add vivisect to my path. 
vivisect-master I used MD5 (vivisect-master.zip) = b9a93f09d87b3f201cf29a18c9d9c095 sha1= 280b299d2ff233f878bdadd66ba87637181a5206
I have no idea what have changed

**Comment by rakuy0** [comment]
Can you re-download the latest vivisect (I don't know what git commit that md5 of vivisect corresponds to, but the latest zip file md5 is `16061452f7eda084c8399ebb91da1584` and I know that one works). Or you can git clone the latest vivisect master branch like so:
`git clone https://github.com/vivisect/vivisect.git`

That way we're at least on the same version, which should make debugging easier.

**Comment by maoguai** [comment]
![image](https://user-images.githubusercontent.com/21984318/79947206-2183a500-84a4-11ea-80a7-2cba22d87af0.png)
I have updated to the lastest vivisect, but it still doesn't work in python 2.7. could you make it work in python 2.7?
![image](https://user-images.githubusercontent.com/21984318/79947246-352f0b80-84a4-11ea-9161-3871742268fe.png)

**Comment by rakuy0** [comment]
It works for me on python 2.7.15 just as you're doing it, which makes me think something else is going on, like a mismatched path or you're colliding with something else like floss.

If you do `import vstruct`, and assuming that doesn't blow up, and then `print(vstruct.__file__)`, what comes out?

And if you just try to run vivbin directly using python, what happens?

**Comment by maoguai** [comment]
![image](https://user-images.githubusercontent.com/21984318/80000970-6a614b00-84f0-11ea-846b-05ba6750dd7a.png)
Is problem happened in there?

**Comment by rakuy0** [comment]
Yea, you have some conflicting versions of vivisect on your machine, one you seem to have installed via pip and another you're trying to just download and use. The constants module should still exist, which is odd, but conflicting versions are weird, so as a final check, can you do `import vstruct.constants` and `print(vstructs.constants.__file__)`?

But best to just remove the old version in any case and see if that fixes it.

**Comment by maoguai** [comment]
ohh,i probably find the mistake that is mismatched path. I delete the vstruct file in python and now it works. Thanks for your patient reply. vivisect is very useful

**Comment by williballenthin** [comment]
i bet this guy was the culprit: https://pypi.org/project/vivisect-vstruct-wb/ 😇
