### ISSUE TITLE
pe: parse imports from the delay import table

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#297]
viv doesn't parse the [Delay Load Import Table](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#delay-load-import-tables-image-only) when recovering imports. while its true that this table *can* contain anything, there's a convention for the interpretation, so a parser can probably detect when its well formed and extract the imports. more details [here](https://reverseengineering.stackexchange.com/questions/16261/should-the-delay-import-directory-contain-virtual-addresses)

**Comment by williballenthin** [comment]
i can probably submit a PR adding this feature

**Comment by rakuy0** [comment]
I'd be happy to review and get a PR for this in. Might take a bit otherwise.

**Comment by rakuy0** [comment]
Added in #331 and will be released in vivisect pypi release 0.2.0.
