### ISSUE TITLE
PE: Read gave wrong length

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#346]
originally reported here: https://github.com/fireeye/capa/issues/385

```
> vivbin 40c0a313897b26e14e54683ceace4a161859f368b0114a2ca614deca3b2ca5da
Traceback (most recent call last):
  File "/home/user/env2/bin/vivbin", line 11, in <module>
    load_entry_point('vivisect', 'console_scripts', 'vivbin')()
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 100, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2629, in loadFromFile
    fname = mod.parseFile(self, filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 37, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 346, in loadPeIntoWorkspace
    mapoffset = vw.readMemoryPtr(rva + baseaddr) - baseaddr
  File "/home/user/code/vivisect/envi/memory.py", line 189, in readMemoryPtr
    return self.readMemValue(va, self.imem_psize)
  File "/home/user/code/vivisect/envi/memory.py", line 178, in readMemValue
    raise Exception("Read gave wrong length at va: 0x%.8x (wanted %d got %d)" % (addr, size, len(bytes)))
Exception: Read gave wrong length at va: 0x140000ffc (wanted 8 got 4)
```

**Comment by williballenthin** [comment]
exception is here:
https://github.com/vivisect/vivisect/blob/master/vivisect/parsers/pe.py#L346

attempting to read 8 bytes, only 4 available.

memory map at this point during loading:

![image](https://user-images.githubusercontent.com/156560/106167903-eefd8b80-614a-11eb-9714-8021337d1696.png)

PE section headers:
![image](https://user-images.githubusercontent.com/156560/106168230-44399d00-614b-11eb-9cf5-fd078de76bc5.png)

looks like the relocation is split across PE header page and the first section???

**Comment by williballenthin** [comment]
ah, but the PE doesn't load in Windows:

![image](https://user-images.githubusercontent.com/156560/106169426-99c27980-614c-11eb-9792-5275d3d74ac3.png)

**Comment by williballenthin** [comment]
by skipping the single invalid relocation, the PE loads and can be analyzed by viv. this is technically less correct, but would enable analysis against more executables. I'll open a PR with this fix.

**Comment by rakuy0** [comment]
Being able to analyze even corrupt files, so long as it's not a horrific effort to bend over backwards to parse it.

So #347 is merged. Thank you sir :+1:
