### ISSUE TITLE
switch table regression in v0.2.0

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#348]
During upgrade of vivisect in capa, we found that one of our [test cases newly failed](https://github.com/fireeye/capa/pull/413). We traced this to a regression in vivisect's switch case analysis released with v0.2.0.

to reproduce:

[mimikatz.exe](https://github.com/fireeye/capa-testfiles/blob/master/mimikatz.exe_) (32-bit)
function: 0x0046d6ce
indirect jump at: 0x46D7D8
*want* to see instructions recognized at addresses: 0x46D9CA, 0x46D7DF, and 0x46DA23

in v0.1.0, vivisect successfully explored many instructions following this indirect jump. in v0.2.0, vivisect is stymied.

![image](https://user-images.githubusercontent.com/156560/106654221-155d6580-6555-11eb-9b2d-ff5fdf101ef7.png)
![image](https://user-images.githubusercontent.com/156560/106654249-1ee6cd80-6555-11eb-94ad-8716cb5ef427.png)

**Comment by williballenthin** [comment]
this is probably a blocking issue for us before we upgrade capa to use viv v0.2.x.

**Comment by rakuy0** [comment]
Probably. I'm triaging it now. I can easily replicate it, which is nice. I'll ping you when I put up a PR for it.

**Comment by Ana06** [comment]
It seems this is fixed in master with Python 3: https://github.com/fireeye/capa/pull/421

**Comment by williballenthin** [comment]
@rakuy0  can we get one last v0.2.1 on the py2 branch to address this? capa is migrating to py3 after one final minor release that should incorporate this fix, so i don't expect we'll have further requests for the py2 branch beyond this.

**Comment by rakuy0** [comment]
Yea, juuuust threw up a branch. Just needed a bit of time to get back to it since I've been swamped recently.

**Comment by rakuy0** [comment]
@williballenthin @Ana06 0.2.1 should be up on pypi. Let me know if it works for you.

**Comment by Ana06** [comment]
It does, thanks @rakuy0!

**Comment by williballenthin** [comment]
thank you @rakuy0 !
