### ISSUE TITLE
Bug in getSegment(va) (vivisect 1.0.0)

### ISSUE THREAD

**Issue by Ana06** [vivisect/vivisect#370]
`vw.getSegment(0x4BA190)` for the file https://github.com/fireeye/capa-testfiles/blob/master/mimikatz.exe_ returns `None` with vivisect 1.0.0 while it used to return `(4939776, 16840, '.data', 'mimikatz')` in vivisect 0.1.0. As the `.data` section starts at 0x4B6000 and has a virtual size of 0x41C8, I think that the output of vivisect 0.1.0 was correct and that this is a bug introduced in the last release. As this makes capa failing and last time I tried it (I think with 38a3fc23dbe79cd55335b57aa3587c05f3fb1d72) that was not the case, I think this has been introduced in one of the last 5 commits.

## Steps to reproduce
```
import vivisect
file = 'mimikatz.exe_' # https://github.com/fireeye/capa-testfiles/blob/master/mimikatz.exe_
vw = vivisect.VivWorkspace()
vw.getSegment(0x4BA190)
```

**Comment by williballenthin** [comment]
`(4939776, 16840, '.data', 'mimikatz')` decodes to:
section `.data` in `mimikatz` starting at `0x4b6000`-`0x4ba1c8`

`0x4BA190` is strictly in this range, so it certainly should not return `None`.

**Comment by rakuy0** [comment]
Ah. I know what happened and have a fix for it. I'm writing some tests for it and I'll have a PR up for it later today.
