### ISSUE TITLE
release v1.0.4

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#410]
can you publish a point release soonish? we're interested to incorporate the latest x86 emu fixes into an upcoming release of floss.

**Comment by atlas0fd00m** [comment]
hey @williballenthin , 
we have some more emulator fixes in the mix, would you like us to do the release first, or cut the release after we merge in the changes in https://github.com/vivisect/vivisect/pull/405 (which we can increase the immediacy after tomorrow)?

**Comment by rakuy0** [comment]
I'm also about to throw up another PR that fixes some errors that definitely shouldn't make it into another release. So I think after we get those in we'll be good to cut another release.

**Comment by williballenthin** [comment]
> you like us to do the release first, or cut the release after we merge

thanks for the offer! we'd be happy with a release within approx 1 month, so just starting the discussion now. no need to rush out any release before #405 etc.

**Comment by williballenthin** [comment]
i have a few more bugs to report and PRs to submit. then, we'd love to get a capa release out with the enhanced emulation and PE parsing.

**Comment by williballenthin** [comment]
for fun, you can see the upcoming issues here: https://github.com/fireeye/capa/milestone/12

**Comment by atlas0fd00m** [comment]
cool! thanks.
@williballenthin what's the "aa64" support that CAPA has?  we have aarch64 support in an alpha state sitting in a branch, but that's it so far.

**Comment by williballenthin** [comment]
> what's the "aa64" support that CAPA has?

it doesn't have any. i suppose this might kinda sorta work cause viv *might* not complain, but we're not explicitly supporting non-intel yet.

**Comment by williballenthin** [comment]
we'd like to do a capa release at the start of next week. would you please do a viv (patch) release tomorrow afternoon? while i'd love to wait for all pending features, its even more useful to make use of the enhancements that we do have merged.

i have two more small PE bugs to report and fix later today.
ideally #405 and #411 would make it in too, but i'm not sure on their status?

**Comment by williballenthin** [comment]
all my identified issues are in (with pending PRs, too!).

**Comment by williballenthin** [comment]
https://github.com/vivisect/vivisect/releases/tag/v1.0.4
