### ISSUE TITLE
elf: analysis regression in v1.0.4

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#445]
as originally identified by @TcM1911 in https://github.com/fireeye/capa/issues/744, v1.0.4 regresses in its analysis coverage of ELF binaries.

to reproduce, i've developed [a script](https://gist.github.com/williballenthin/8566a1043532479c51ebb22a5b590db1) that can be run upon various viv tags and summarizes analysis coverage. we can optionally consider incorporating this script into viv proper and/or its CI.

here are results against two linux ELF files:

### RedXor malware / 7351f8a40c5450557b24622417fc478d
https://www.virustotal.com/gui/file/0423258b94e8a9af58ad63ea493818618de2d8c60cf75ec7980edcaa34dcc919/detection

![image](https://user-images.githubusercontent.com/156560/131014879-cbd0f68d-ceb2-4819-8914-8c7c2fc962aa.png)

### sudo / 9fd556b58393b71d64da277c8f782ef4d1dccffd007495709375d2efa85d1248
https://www.virustotal.com/gui/file/9fd556b58393b71d64da277c8f782ef4d1dccffd007495709375d2efa85d1248/detection

![image](https://user-images.githubusercontent.com/156560/131015036-d79fd910-5b21-4576-ac23-bd385a638822.png)

**Comment by mr-tz** [comment]
If I restore `vivisect/analysis/elf/elfplt.py` from a7b5f8deef35dca1a31fe7ac6ff7732578cc3e76 I get better results again
```
2021-08-31 15:51:04,906:INFO:vivisect: Percentage of discovered executable surface area: 76.1% (91447 / 120100)[__init__.py:vprint:181:MainThread]
2021-08-31 15:51:04,906:INFO:vivisect:    Xrefs/Blocks/Funcs:                             (7083 / 2561 / 297)[__init__.py:vprint:181:MainThread]
2021-08-31 15:51:04,906:INFO:vivisect:    Locs,  Ops/Strings/Unicode/Nums/Ptrs/Vtables:   (17558:  15892 / 664 / 0 / 78 / 82 / 0)[__init__.py:vprint:181:MainThread]
2021-08-31 15:51:04,906:INFO:vivisect: stats: {'functions': 297, 'relocations': 80}[vivbin.py:main:128:MainThread]
```

Can you give an estimate on when you can track this down or provide pointers for me to find the issue here?

**Comment by rakuy0** [comment]
So I have one fix down. It fixes one file (9fd556b58393b71d64da277c8f782ef4d1dccffd007495709375d2efa85d1248) and most of the other (0423258b94e8a9af58ad63ea493818618de2d8c60cf75ec7980edcaa34dcc919). I tracked down the second of my issues with the second binary, so now I'm mostly writing scripts to pull features from one version of synapse and bring them forward so I can encode a more explicit test on these binaries.

I should have a PR up later this week depending on my schedule and whether or not Tropical Storm Ida knocks my power out.

**Comment by mr-tz** [comment]
Sounds great. Thanks for your work and the update!
