### ISSUE TITLE
Default View For Vivbin

### ISSUE THREAD

**Issue by TomSomerville** [vivisect/vivisect#521]
Requesting a default view be implemented, instead of the blank canvas that is currently default. 
Something that one could do very basic beginner RE CTFs with out of the box. Rather than having to spend time learning / setting up the GUI. 

Make me not hunt for default.lyt

**Comment by rakuy0** [comment]
A good idea :+1:

**Comment by atlas0fd00m** [comment]
don't hunt for it!  we created something just for you!

```
View->Layouts->Load Base Default
```

see #643
