### ISSUE TITLE
getBranches may return (None, flags) - expected

### ISSUE THREAD

**Issue by mr-tz** [vivisect/vivisect#574]
`getBranches` returns a list of tuples with (target VA of the branch, possible set of flags).

I think we should guard against VA being `None` like in the example below or are callers expected to check this (some vivisect internal calls do so)? For the latter, the documentation should at least be updated.

```asm
.text:001A1325 68 00 80 00 00                    push    8000h
.text:001A132A 53                                push    ebx
.text:001A132B FF B5 A8 FC FF FF                 push    [ebp+lpParameters]
.text:001A1331 FF D6                             call    esi ; dword_1AC0EC
.text:001A1333
.text:001A1333                   loc_1A1333:                             ; CODE XREF: sub_1A1112+E5↑j
.text:001A1333                                                           ; sub_1A1112+211↑j
.text:001A1333 8B 4D FC                          mov     ecx, [ebp+var_4]
```
- from the sample linked in https://github.com/mandiant/flare-floss/issues/617#issuecomment-1381120965

`getBranches()` on the `call esi` returns `[(0x1A1333, 65552), (None, 65537)]`

`(None, 65537)` appears because `getOperValue()` returns `None` for `esi` (without an emulator).

**Comment by atlas0fd00m** [comment]
this is intended behavior, and allows the code-flow engine to tag dynamic branches (which is later used to look for and analyze switch-cases).

**Comment by atlas0fd00m** [comment]
you're correct about the documentation.
