### ISSUE TITLE
Vdb exec inversed logic of continue after attached.

### ISSUE THREAD

**Issue by bat-serjo** [vivisect/vivisect#58]
By default "config -s vdb.BreakOnEntry" is false. But behaves as if true!
example
serj@debian:~/examples/CRACKME$ python ~/netstock/vivisect/vdbbin Crackme
Invalid VDB_EXT_PATH dir: /home/serj/examples/CRACKME/vdb/ext
vdb > config
cli.verbose=false
vdb.BreakOnEntry=false
vdb.BreakOnMain=false
vdb.KillOnQuit=false
vdb.SymbolCacheActive=true
vdb.SymbolCachePath="/home/serj/.envi/symcache"
vdb > exec Crackme

ERROR: (Exception) PT_ATTACH failed! linux platformExec
vdb > exec Crackme
PID 4445 exited: 5 (0x00000005)
vdb > exec Crackme
vdb > Attached to : 4450
Loading Binary: /home/serj/examples/CRACKME/Crackme
Loading Binary: /lib/x86_64-linux-gnu/ld-2.19.so
Loading Binary: [vdso]
Thread: 4450 NOTIFY_BREAK

------------------------------------------------------------------------------------------------
On the oposite when you set it to true - 

vdb > config -s vdb.BreakOnEntry=true
vdb.BreakOnEntry=true
saved configuration file to: /home/serj/.vdb/vdb.json
vdb > config
cli.verbose=false
vdb.BreakOnEntry=true
vdb.BreakOnMain=false
vdb.KillOnQuit=false
vdb.SymbolCacheActive=true
vdb.SymbolCachePath="/home/serj/.envi/symcache"
vdb > exec Crackme
vdb > Exit Thread: 4536 (ecode: 0x00000000 (0))
Attached to : 4536
Loading Binary: /home/serj/examples/CRACKME/Crackme
Loading Binary: /lib/x86_64-linux-gnu/ld-2.19.so
Loading Binary: [vdso]
Thread: 4536 NOTIFY_BREAK
No cookies for you
PID 4536 exited: 0 (0x00000000)

It should have waited in the later example and continue in the first.
Problem was traced back to vdb/__init__.py line (423) and should be replaced with something like:

            # only respect BreakOnEntry if we exec'd something
            if self.config.vdb.BreakOnEntry and trace.hasMeta('ExecCommand'):
                self.runagain = False # skip initial break
            else:
                self.runagain = True

**Comment by invisig0th** [comment]
haha, looks like a good catch! i'll confirm and fix shortly :)

**Comment by bat-serjo** [comment]
Glad to help.
Really like the code base, clean and ordered.


2015-04-11 23:49 GMT+02:00 invisig0th <notifications@github.com>:

**Comment by l1berty** [comment]
The described symptoms appears to be a combination of 2 conditions:
1.  race condition due to parent/child relationship race for PT_TRACE_ME / PT_ATTACH 
(https://github.com/vivisect/vivisect/blob/master/vtrace/platforms/linux.py#L313)
2.  not finding the __entry symbol
(https://github.com/vivisect/vivisect/blob/master/vdb/__init__.py#L78)

For example, I can repro the issue if I peg my other core's and remove the time.sleep call.

This does not appear to be inverted behavior of the BreakOnEntry.  @bat-serjo Can you confirm?

note: still should improve synchronization between parent/child.

**Comment by bat-serjo** [comment]
Yes especially the race between [attach_me, attach] is easily
reproducible on my (weak) machine Sometime i get attached to the children
before it's address space have been repopulated and see the memory map of
the vdb.
I believe the parent must perform wait on the child for (i don't remember
the signals name) and then attach to it.

About the entry point symbol I have not experienced this yet even thou I
played with a little crackme that subverts the entry point.

However these two are independent from the logic behind the vdb
configuration for attach on entry.

2015-04-16 1:55 GMT+02:00 l1berty <notifications@github.com>:

**Comment by bat-serjo** [comment]
After some experimenting in vtrace/platforms/linux.py this seems to be rock solid.
@v_base.threadwrap
    def platformExec(self, cmdline):
        # Very similar to posix, but not
        # quite close enough...
        self.execing = True
        cmdlist = e_cli.splitargs(cmdline)
        os.stat(cmdlist[0])
        
        pid = os.fork() 
        
        # Child will be blocked after execv because of trace me!
        if pid == 0:
            v_posix.ptrace(v_posix.PT_TRACE_ME, 0, 0, 0)
            os.execv(cmdlist[0], cmdlist)
            sys.exit(-1)

        # Parent will wait for the child
        for i in xrange(0, 33):
            rid, status, rusage = os.wait4(pid, os.WCONTINUED | 
                                                os.WUNTRACED  | 
                                                os.WNOHANG)
            if status != 0:
                break
                
        res = v_posix.ptrace(PT_ATTACH, pid, 0, 0)
        if res < 0:
            raise Exception("Oh no can't PTRACE!")
                    
        self.pthreads = [pid,]
        self.setMeta("ExeName", self._findExe(pid))
        return pid


Looks like the logic in vdb is perfectly fine! The problem was in this function.
