### ISSUE TITLE
vstruct primitives don't implement __hash__

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#59]
The vstruct primitives do not implement the `__hash__` operator, which makes them unsuitable for use as keys in `dict` or entries in `set`. Is this intentional, or would you accept a patch adding the `__hash__` operator to integer-like and string-like primitives?

testcase.py:
```
from vstruct import *
from vstruct.primitives import *


def main():
    buf = "\x01\x00\x00\x00"
    a = v_uint32()
    b = v_uint32()

    a.vsParse(buf)
    b.vsParse(buf)

    print(a)
    print(b)
    print(a == b)

    s = set([])
    s.add(a)
    s.add(b)
    print(s)


if __name__ == "__main__":
    main()
```

output: 
```
» python testcase.py
1
1
True
set([1, 1])     # expected: 'set([1])'
```

**Comment by invisig0th** [comment]
I'd accept a __hash__ delta for sure, but we'd probably need to consider what to have them return...

**Comment by williballenthin** [comment]
(Lets ignore that this may already be a code-smell,) since I can already usually treat a parsed `v_uint32` as a number, such as with addition or multiplication, my expectation was that `__hash__` would apply to the underlying data, and not to the instance. I believe the existing default hash already is the instance id (specifically, object address in memory: http://stackoverflow.com/a/11324771/87207, https://docs.python.org/2/library/functions.html#id). I'd propose that for (at least) number-like and string-like vstructs, that `__hash__` be passed to the existing Python-native hash function for the underlying data. Perhaps something like:

```
    def __hash__(self):
        return hash(self.vsGetValue())
```

Upon closer inspection of the module, I see that neither `__cmp__` nor `__eq__` are implemented, so maybe it was explicit decision not to deal with equality. I think that's a fair position, too.


---
ps.

When I go back to my project, I'll clean up some of my leaky abstractions by being more careful to explicitly extract the Python-native data from vstruct instances before passing it to higher logic. I think this is a better solution long term than to blame the library :-)
