### ISSUE TITLE
`v1.1.1` including dynamic import updates

### ISSUE THREAD

**Issue by mr-tz** [vivisect/vivisect#590]
Opening this up here for better visibility. A small point release would great.

              Amazing, thanks for the quick fix. Can you please provide a `v1.1.1` release with these updates?

_Originally posted by @mr-tz in https://github.com/vivisect/vivisect/issues/587#issuecomment-1465234383_

**Comment by mr-tz** [comment]
Friendly bump on this as we're prepping a new capa release and would like to include vivisect improvements.

**Comment by williballenthin** [comment]
they may be patiently awaiting my fixes in #562

**Comment by atlas0fd00m** [comment]
done.
