### ISSUE TITLE
win32 platformResumeThread

### ISSUE THREAD

**Issue by cmaruti** [vivisect/vivisect#61]
Seems that platformResumeThread doesn't work as expected on win32 systems. I track down the problem to the following code fragment (file `vtrace/platforms/win32.py`)

```
def platformResumeThread(self, thrid):
        if kernel32.ResumeThread(thrid) == 0xffffffff:
            raiseWin32Error()
```

Accordingly to the MSDN definition (https://msdn.microsoft.com/en-us/library/windows/desktop/ms685086(v=vs.85).aspx) and also the declaration at line `896` in the aforementioned source file, the function call takes an HANDLE as input parameter. Instead the code pass a the thread id so the final result is not consistent. Make sense?

**Comment by invisig0th** [comment]
Yep! i'll go take a look.  sorry about the laaaag.  :)

**Comment by invisig0th** [comment]
Committed a fix, dunno how that managed to stay dorked so long, thanks!
