### ISSUE TITLE
Missing tarball on PyPI for 1.2.0

### ISSUE THREAD

**Issue by Tatsh** [vivisect/vivisect#656]
https://pypi.org/project/vivisect/#files

This is the same with latest viv-utils https://github.com/williballenthin/viv-utils/issues/168

**Comment by rakuy0** [comment]
Aye, this is fairly easy to fix on the next release (just a flag add to a build script), which I'm hoping will be out sooner rather than later since there's some other small fixes I want to get in.

Thanks for the report :+1:

**Comment by atlas0fd00m** [comment]
all good?  or are we still waiting on 1.2.1?

**Comment by rakuy0** [comment]
1.2.1 is out and PyPI shouls it as having a source tarball.
