### ISSUE TITLE
Relax minimum supported Python version

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#664]
Would you please consider relaxing the minimum supported Python version?

The following commit bumped the MSPV to >= 3.11: https://github.com/vivisect/vivisect/commit/6d760a1c88414c2acd72d9ec9121a74b71415a52#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R13

and this was pulled into the 1.2.0 release (though not documented in the release notes):
https://github.com/vivisect/vivisect/blame/master/pyproject.toml#L13

Via [this page](https://devguide.python.org/versions/), Python versions 3.8-3.12 remain supported, at least at the interpreter level:
![image](https://github.com/user-attachments/assets/195a3aef-8a9b-45cf-9df3-2db86702376d)

Downstream users of vivisect, such as capa, try to support as many non-EOL versions of Python as possible, at least those receiving Python.org support, but these changes restrict them to only 3.11+, which is unfortunate.

**Comment by rakuy0** [comment]
Oh. That was probably me just copypasting stuff I use in other projects into the pyproject.toml. Yea we can relax it.

**Comment by rakuy0** [comment]
1.2.1 is up and relaxes the version to 3.8
