### ISSUE TITLE
Vivisect chokes on this file

### ISSUE THREAD

**Issue by bat-serjo** [vivisect/vivisect#86]
This library chokes vivisect.
https://www.fireeye.com/blog/threat-research/2015/09/flare-on_challenges.html

How do you upload files here ?!?

It comes from the flare-on challenge. Level 6.
Validates the input. Should return "That's it!". 
Basically forces you to enter the email your self.

```
libvalidate.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped

serj@debian:~/examples/CRACKME/FLARE/6$ ~/netstock/vivisect/vivbin -B ./libvalidate.so                                                                                                          
Traceback (most recent call last):                                                                                                                                                              
File "/home/serj/netstock/vivisect/vivbin", line 142, in <module>                                                                                                                             
    main()                                                                                                                                                                                      
File "/home/serj/netstock/vivisect/vivbin", line 98, in main                                                                                                                                  
    vw.loadFromFile(fname, fmtname=parsemod)                                                                                                                                                    
File "/home/serj/netstock/vivisect/vivisect/__init__.py", line 2071, in loadFromFile                                                                                                          
    fname = mod.parseFile(self, filename)                                                                                                                                                       
File "/home/serj/netstock/vivisect/vivisect/parsers/elf.py", line 15, in parseFile                                                                                                            
    return loadElfIntoWorkspace(vw, elf, filename=filename)                                                                                                                                     
File "/home/serj/netstock/vivisect/vivisect/parsers/elf.py", line 92, in loadElfIntoWorkspace                                                                                                 
    platform = elf.getPlatform()                                                                                                                                                                
File "/home/serj/netstock/vivisect/Elf/__init__.py", line 535, in getPlatform                                                                                                                 
    for note in self.getNotes():                                                                                                                                                                
File "/home/serj/netstock/vivisect/Elf/__init__.py", line 524, in getNotes                                                                                                                    
    offset = note.vsParse(notebytes,offset=offset)                                                                                                                                              
File "/home/serj/netstock/vivisect/vstruct/__init__.py", line 143, in vsParse                                                                                                                 
    offset = fobj.vsParse(sbytes, offset=offset)                                                                                                                                                
File "/home/serj/netstock/vivisect/vstruct/primitives.py", line 147, in vsParse                                                                                                               
    self._vs_value = struct.unpack(self._vs_fmt, b)[0]                                                                                                                                          
struct.error: unpack requires a string argument of length 4                                                                                                                                     
serj@debian:~/examples/CRACKME/FLARE/6$
```

after some dirty pcatching i got

```
Loaded (0.1182 sec) ./libvalidate.so
parseOpcode error at 0x0200141f: InvalidInstruction("p_mult: invalid instruction 'd10f2a07' at 0x2001427L",)
parseOpcode error at 0x02001c15: InvalidInstruction("p_mult: invalid instruction 'b50f1c87' at 0x2001c1dL",)
parseOpcode error at 0x020017a7: InvalidInstruction("p_mult: invalid instruction 'b5041cc7' at 0x20017afL",)
parseOpcode error at 0x0200132d: InvalidInstruction("p_uncond (ontop=0): invalid instruction '6c7047f0' at 0x2001335L",)
parseOpcode error at 0x02001331: InvalidInstruction("p_uncond (ontop=2): invalid instruction 'b5cb6bf9' at 0x2001339L",)
parseOpcode error at 0x02001469: InvalidInstruction("p_mult: invalid instruction 'd10f2a07' at 0x2001471L",)
parseOpcode error at 0x02000e71: local variable 'Rn' referenced before assignment
ANALYSIS TIME: 0.89896607399
stats: {'functions': 38, 'relocations': 0}
Saving workspace: ./libvalidate.so.viv


~/netstock/vivisect/vivbin  ./libvalidate.so.viv 
Loaded (0.0172 sec) ./libvalidate.so.viv
```

So far so good. Strings workspaces are there. Elf structures are parsed. Imports, Exports. Some functions exit but they don't look very good.
At one point we start getting this error 

```
.text:0x020013f3  FUNC: void unknown libvalidate._Unwind_DeleteException( ) [1 XREFS]
.text:0x020013f3  
.text:0x020013f3  Stack Variables:
.text:0x020013f3  
.text:0x020013f3  b5836801         streqh r8,[r8, #-0x35]!
.text:0x020013f7  1c002b01         bxeq r12
.text:0x020013fb  d0012098         stmloda r0!,{r4, r6, r7, r8, }
.text:0x020013ff  4708bd10         adcnes r0,sp,r7, asr #16
.text:0x02001403  
.text:0x02001403  FUNC: void unknown libvalidate._Unwind_VRS_Get( ) [0 XREFS]
.text:0x02001403  
.text:0x02001403  Stack Variables:
.text:0x02001403  
.text:0x02001403  b5041c04         ldreq r0,[r12] #-0x4b5
.text:0x02001407  2913d808         ldmeqia r8,{r0, r3, r5, r8, r9, r12, }^
.text:0x0200140b  1c00f072         rscvcs r0,r0,#0x1c
.text:0x0200140f  fd050311         strned r0,[r3, -sp]
.text:0x02001413  03030001         mrseq r0,
Render Exception At 0x2001413L: cannot concatenate 'str' and 'NoneType' objects
.text:0x02001413  03030001         mrseq r0,
Exception At 0x2001413L: Traceback (most recent call last):
File "/home/serj/netstock/vivisect/envi/memcanvas/__init__.py", line 304, in renderMemoryAppend
    rsize = rend.render(self, va)
File "/home/serj/netstock/vivisect/vivisect/renderers/__init__.py", line 51, in render
    self.renderLocation(mcanv, loc, name, func, cmnt, extra)
File "/home/serj/netstock/vivisect/vivisect/renderers/__init__.py", line 158, in renderLocation
    mcanv.addText("Opcode Render Failed: %s\n" % repr(extra))
File "/home/serj/netstock/vivisect/envi/archs/arm/disasm.py", line 1461, in __repr__
    x.append(o.repr(self))
File "/home/serj/netstock/vivisect/envi/archs/arm/disasm.py", line 2089, in repr
    return psrs[self.psr] + '_' + fields[self.val]
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Also code analisys doesn't do well.

```
.text:0x02000e65  FUNC: void unknown libvalidate.Java_com_flareon_flare_ValidateActivity_validate( ) [0 XREFS]
.text:0x02000e65  
.text:0x02000e65  Stack Variables:
.text:0x02000e65  
.text:0x02000e65  b5504c05         streqb r5,[r12, #-0xb5]
.text:0x02000e69  1c0021a5         strge r0,[r1, #-0x1c]!
.text:0x02000e6d  4402921e         cdpne p2,9,c0,c2,c4,2
.text:0x02000e71  a8
.text:0x02000e72  4e
.text:0x02000e73  4a
.text:0x02000e74  01
.text:0x02000e75  f0
.text:0x02000e76  48
.text:0x02000e77  f8
.text:0x02000e78  4d
.text:0x02000e79  49
.text:0x02000e7a  5c
.text:0x02000e7b  22
```

And some like this occurs 

```
.plt:0x02000de4  
.plt:0x02000de4  FUNC: void unknown sub_02000de4( ) [1 XREFS]
.plt:0x02000de4  
.plt:0x02000de4  Stack Variables:
.plt:0x02000de4  
.plt:0x02000de4  00c68fe2         adr r12,loc_02000dec
.plt:0x02000de8  04ca8ce2         add r12,r12,#0x4000
.plt:0x02000dec  loc_02000dec: [1 XREFS]
.plt:0x02000dec  00f2bce5         ldr pc,[r12, #0x200]!
.plt:0x02000df0  00
.plt:0x02000df1  c6
.plt:0x02000df2  8f
.plt:0x02000df3  e2
.plt:0x02000df4  loc_02000df4: [1 XREFS]
.plt:0x02000df4  04
.plt:0x02000df5  ca
.plt:0x02000df6  8c
.plt:0x02000df7  e2
.plt:0x02000df8  f8
.plt:0x02000df9  f1
.plt:0x02000dfa  bc
```

**Comment by atlas0fd00m** [comment]
sergey,

could you please send the library to my email address atlas@r4780y.com?

thanks,
@

On Tuesday, September 22, 2015 11:57:31 AM Sergey Kostov wrote:
> This library chokes vivisect.
> It comes from the flare-on challenge. Level 6.
> Validates the input. Should return "That's it!".
> Basically forces you to enter the email your self.
> 
> 	libvalidate.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV),
> dynamically linked, interpreter /system/bin/linker, stripped
> 
> 	serj@debian:~/examples/CRACKME/FLARE/6$ ~/netstock/vivisect/vivbin -B
> ./libvalidate.so Traceback (most recent call last):
> 	File "/home/serj/netstock/vivisect/vivbin", line 142, in <module>
> 		main()
> 	File "/home/serj/netstock/vivisect/vivbin", line 98, in main
> 		vw.loadFromFile(fname, fmtname=parsemod)
> 	File "/home/serj/netstock/vivisect/vivisect/__init__.py", line 2071, in
> loadFromFile fname = mod.parseFile(self, filename)
> 	File "/home/serj/netstock/vivisect/vivisect/parsers/elf.py", line 15, in
> parseFile return loadElfIntoWorkspace(vw, elf, filename=filename)
> 	File "/home/serj/netstock/vivisect/vivisect/parsers/elf.py", line 92, in
> loadElfIntoWorkspace platform = elf.getPlatform()
> 	File "/home/serj/netstock/vivisect/Elf/__init__.py", line 535, in
> getPlatform for note in self.getNotes():
> 	File "/home/serj/netstock/vivisect/Elf/__init__.py", line 524, in getNotes
> 		offset = note.vsParse(notebytes,offset=offset)
> 	File "/home/serj/netstock/vivisect/vstruct/__init__.py", line 143, in
> vsParse offset = fobj.vsParse(sbytes, offset=offset)
> 	File "/home/serj/netstock/vivisect/vstruct/primitives.py", line 147, in
> vsParse self._vs_value = struct.unpack(self._vs_fmt, b)[0]
> 	struct.error: unpack requires a string argument of length 4
> 	serj@debian:~/examples/CRACKME/FLARE/6$
> 
> after some dirty pcatching i got
> 
> 	Loaded (0.1182 sec) ./libvalidate.so
> 	parseOpcode error at 0x0200141f: InvalidInstruction("p_mult: invalid
> instruction 'd10f2a07' at 0x2001427L",) parseOpcode error at 0x02001c15:
> InvalidInstruction("p_mult: invalid instruction 'b50f1c87' at 0x2001c1dL",)
> parseOpcode error at 0x020017a7: InvalidInstruction("p_mult: invalid
> instruction 'b5041cc7' at 0x20017afL",) parseOpcode error at 0x0200132d:
> InvalidInstruction("p_uncond (ontop=0): invalid instruction '6c7047f0' at
> 0x2001335L",) parseOpcode error at 0x02001331: InvalidInstruction("p_uncond
> (ontop=2): invalid instruction 'b5cb6bf9' at 0x2001339L",) parseOpcode
> error at 0x02001469: InvalidInstruction("p_mult: invalid instruction
> 'd10f2a07' at 0x2001471L",) parseOpcode error at 0x02000e71: local variable
> 'Rn' referenced before assignment ANALYSIS TIME: 0.89896607399
> 	stats: {'functions': 38, 'relocations': 0}
> 	Saving workspace: ./libvalidate.so.viv
> 
> 
> 	~/netstock/vivisect/vivbin  ./libvalidate.so.viv
> 	Loaded (0.0172 sec) ./libvalidate.so.viv
> 
> So far so good. Strings workspaces are there. Elf structures are parsed.
> Imports, Exports. Some functions exit but they don't look very good. At one
> point we start getting this error
> 
> 	.text:0x020013f3  FUNC: void unknown libvalidate._Unwind_DeleteException( 
)
> [1 XREFS] .text:0x020013f3
> 	.text:0x020013f3  Stack Variables:
> 	.text:0x020013f3
> 	.text:0x020013f3  b5836801         streqh r8,[r8, #-0x35]!
> 	.text:0x020013f7  1c002b01         bxeq r12
> 	.text:0x020013fb  d0012098         stmloda r0!,{r4, r6, r7, r8, }
> 	.text:0x020013ff  4708bd10         adcnes r0,sp,r7, asr #16
> 	.text:0x02001403
> 	.text:0x02001403  FUNC: void unknown libvalidate._Unwind_VRS_Get( ) [0
> XREFS] .text:0x02001403
> 	.text:0x02001403  Stack Variables:
> 	.text:0x02001403
> 	.text:0x02001403  b5041c04         ldreq r0,[r12] #-0x4b5
> 	.text:0x02001407  2913d808         ldmeqia r8,{r0, r3, r5, r8, r9, r12, }^
> 	.text:0x0200140b  1c00f072         rscvcs r0,r0,#0x1c
> 	.text:0x0200140f  fd050311         strned r0,[r3, -sp]
> 	.text:0x02001413  03030001         mrseq r0,
> 	Render Exception At 0x2001413L: cannot concatenate 'str' and 'NoneType'
> objects .text:0x02001413  03030001         mrseq r0,
> 	Exception At 0x2001413L: Traceback (most recent call last):
> 	File "/home/serj/netstock/vivisect/envi/memcanvas/__init__.py", line 304,
> in renderMemoryAppend rsize = rend.render(self, va)
> 	File "/home/serj/netstock/vivisect/vivisect/renderers/__init__.py", line
> 51, in render self.renderLocation(mcanv, loc, name, func, cmnt, extra)
> 	File "/home/serj/netstock/vivisect/vivisect/renderers/__init__.py", line
> 158, in renderLocation mcanv.addText("Opcode Render Failed: %s\n" %
> repr(extra))
> 	File "/home/serj/netstock/vivisect/envi/archs/arm/disasm.py", line 1461, 
in
> __repr__ x.append(o.repr(self))
> 	File "/home/serj/netstock/vivisect/envi/archs/arm/disasm.py", line 2089, 
in
> repr return psrs[self.psr] + '_' + fields[self.val]
> 	TypeError: cannot concatenate 'str' and 'NoneType' objects
> 
> 
> Also code analisys doesn't do well.
> 
> 	.text:0x02000e65  FUNC: void unknown
> libvalidate.Java_com_flareon_flare_ValidateActivity_validate( ) [0 XREFS]
> .text:0x02000e65
> 	.text:0x02000e65  Stack Variables:
> 	.text:0x02000e65
> 	.text:0x02000e65  b5504c05         streqb r5,[r12, #-0xb5]
> 	.text:0x02000e69  1c0021a5         strge r0,[r1, #-0x1c]!
> 	.text:0x02000e6d  4402921e         cdpne p2,9,c0,c2,c4,2
> 	.text:0x02000e71  a8
> 	.text:0x02000e72  4e
> 	.text:0x02000e73  4a
> 	.text:0x02000e74  01
> 	.text:0x02000e75  f0
> 	.text:0x02000e76  48
> 	.text:0x02000e77  f8
> 	.text:0x02000e78  4d
> 	.text:0x02000e79  49
> 	.text:0x02000e7a  5c
> 	.text:0x02000e7b  22
> 
> And some like this occurs
> 
> 	.plt:0x02000de4
> 	.plt:0x02000de4  FUNC: void unknown sub_02000de4( ) [1 XREFS]
> 	.plt:0x02000de4
> 	.plt:0x02000de4  Stack Variables:
> 	.plt:0x02000de4
> 	.plt:0x02000de4  00c68fe2         adr r12,loc_02000dec
> 	.plt:0x02000de8  04ca8ce2         add r12,r12,#0x4000
> 	.plt:0x02000dec  loc_02000dec: [1 XREFS]
> 	.plt:0x02000dec  00f2bce5         ldr pc,[r12, #0x200]!
> 	.plt:0x02000df0  00
> 	.plt:0x02000df1  c6
> 	.plt:0x02000df2  8f
> 	.plt:0x02000df3  e2
> 	.plt:0x02000df4  loc_02000df4: [1 XREFS]
> 	.plt:0x02000df4  04
> 	.plt:0x02000df5  ca
> 	.plt:0x02000df6  8c
> 	.plt:0x02000df7  e2
> 	.plt:0x02000df8  f8
> 	.plt:0x02000df9  f1
> 	.plt:0x02000dfa  bc
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vivisect/vivisect/issues/86

-- 
3031303030303131303131303131313130313130313130313031313030313031303031303030303030313130313131303031313031313131303031303030303030313130303131303031313130313031303131313030313030313131303130303031313031303030303131303031303130313131303031303030313031313030303031303030303030313130303131303031313031313131303131313030313030303130303030303031313030313030303131303031303130313130303030313031313130313030303131303130303030303130303030303031313030303031303131313031313130313130303030313031313031303031303131313031303030313131303031313030313030303030303131313130303130313130313131313031313130313031303031303030303030313130303030313031313031313030303131303131303030303130303030303031313130313131303131303130303130313131303130303031313031303030303031303030303030313130313131303031313030303031303131313030313130313131303130303031313131303031303031303131303030303130303030303031313030303130303131303130303130313130303131313030313031313030303031303030303030313131303030303031313031313131303131303130303130313130313131303031313130313030303131313130303130303130303030303031313130313030303131303031303130313130303130313031313130313030303131303130303030303030313031300A
